import { Company } from './types';

export const bhikharamChandmal: Company = {
  id: 'bhikharam-chandmal',
  name: 'Bhikharam Chandmal',
  slug: 'bhikharam-chandmal',
  description: 'Authentic Indian sweets and snacks that bring traditional flavors to your table. A heritage brand known for quality mithai, namkeen, and traditional delicacies.',
  website: 'https://bhikharamchandmal.in/',
  logo: 'https://bhikharamchandmal.in/pub/media/logo/default/bhikharam-logo.png',
  coverImage: 'https://bhikharamchandmal.in/pub/media/wysiwyg/slider/banner-2.jpg',
  category: 'Snacks, Sweets & Traditional Foods',
  brandColors: {
    primary: '#A93118',
    secondary: '#8B4513',
    accent: '#D2722F'
  },
  contact: {
    email: 'info@bhikharamchandmal.in',
    website: 'https://bhikharamchandmal.in/'
  },
  specialties: [
    'Traditional Indian Sweets',
    'Premium Namkeen',
    'Festival Specials',
    'Gift Boxes',
    'Heritage Recipes'
  ],
  certifications: [
    'FSSAI Certified',
    'ISO 22000:2018',
    'Halal Certified',
    'Quality Assured'
  ],
  stats: {
    totalProducts: 20,
    avgRating: 4.7,
    yearsOfPartnership: 3
  },
  products: [
    {
      id: 'bc-1',
      title: 'Anjeer Delight',
      url: 'https://bhikharamchandmal.in/sweets/anjeer-delight.html',
      image: 'https://bhikharamchandmal.in/pub/media/catalog/product/a/n/anjeer-delight.jpg',
      price: 449,
      category: 'Sweets',
      subcategory: 'Premium Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      description: 'Premium anjeer (fig) based sweet delicacy with rich taste and texture',
      tags: ['sweets', 'anjeer', 'premium', 'traditional']
    },
    {
      id: 'bc-2',
      title: 'Besan Laddu',
      url: 'https://bhikharamchandmal.in/sweets/besan-ladoo.html',
      image: null,
      price: 150,
      category: 'Sweets',
      subcategory: 'Traditional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      description: 'Classic besan laddu made with pure ghee and traditional methods',
      tags: ['sweets', 'laddu', 'besan', 'ghee', 'traditional']
    },
    {
      id: 'bc-3',
      title: 'Bikaneri Rasgulla',
      url: 'https://bhikharamchandmal.in/sweets/rasgulla.html',
      image: null,
      price: 150,
      category: 'Sweets',
      subcategory: 'Traditional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'rasgulla', 'bikaneri', 'traditional']
    },
    {
      id: 'bc-4',
      title: 'Boondi Laddu',
      url: 'https://bhikharamchandmal.in/sweets/boondi-laddu.html',
      image: null,
      price: 375,
      category: 'Sweets',
      subcategory: 'Traditional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'laddu', 'boondi', 'traditional']
    },
    {
      id: 'bc-5',
      title: 'Cham Cham',
      url: 'https://bhikharamchandmal.in/sweets/cham-cham.html',
      image: null,
      price: 360,
      category: 'Sweets',
      subcategory: 'Bengali Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'cham-cham', 'bengali', 'traditional']
    },
    {
      id: 'bc-6',
      title: 'Chocolate Soan Papdi',
      url: 'https://bhikharamchandmal.in/sweets/soanpapdi-chocolate.html',
      image: null,
      category: 'Sweets',
      subcategory: 'Soan Papdi',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'soan-papdi', 'chocolate', 'modern']
    },
    {
      id: 'bc-7',
      title: 'Coconut Dryfruit Gujia',
      url: 'https://bhikharamchandmal.in/sweets/gunjia-1.html',
      image: null,
      price: 350,
      category: 'Sweets',
      subcategory: 'Festival Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'gujia', 'coconut', 'dryfruit']
    },
    {
      id: 'bc-8',
      title: 'Coconut Soan Papdi',
      url: 'https://bhikharamchandmal.in/sweets/coconut-soan-papdi.html',
      image: null,
      category: 'Sweets',
      subcategory: 'Soan Papdi',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'soan-papdi', 'coconut']
    },
    {
      id: 'bc-9',
      title: 'Dry Petha',
      url: 'https://bhikharamchandmal.in/sweets/dry-petha.html',
      image: null,
      price: 230,
      category: 'Sweets',
      subcategory: 'Regional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'petha', 'dry', 'agra']
    },
    {
      id: 'bc-10',
      title: 'Gulab Jamun',
      url: 'https://bhikharamchandmal.in/sweets/gulab-jamun-product.html',
      image: null,
      price: 150,
      category: 'Sweets',
      subcategory: 'Traditional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'gulab-jamun', 'traditional', 'popular']
    },
    {
      id: 'bc-11',
      title: 'Kaju Katli',
      url: 'https://bhikharamchandmal.in/sweets/kaju-katli.html',
      image: null,
      price: 349,
      category: 'Sweets',
      subcategory: 'Premium Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'kaju-katli', 'cashew', 'premium']
    },
    {
      id: 'bc-12',
      title: 'Kaju Roll',
      url: 'https://bhikharamchandmal.in/sweets/kaju-roll.html',
      image: null,
      price: 349,
      category: 'Sweets',
      subcategory: 'Premium Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'kaju-roll', 'cashew', 'premium']
    },
    {
      id: 'bc-13',
      title: 'Kesar Cham Cham',
      url: 'https://bhikharamchandmal.in/sweets/kesar-cham-cham.html',
      image: null,
      price: 360,
      category: 'Sweets',
      subcategory: 'Bengali Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'cham-cham', 'kesar', 'saffron']
    },
    {
      id: 'bc-14',
      title: 'Kesar Pedha',
      url: 'https://bhikharamchandmal.in/sweets/kesar-peda.html',
      image: null,
      price: 349,
      category: 'Sweets',
      subcategory: 'Premium Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'pedha', 'kesar', 'saffron']
    },
    {
      id: 'bc-15',
      title: 'Kesar-Baati',
      url: 'https://bhikharamchandmal.in/sweets/kesar-baati.html',
      image: null,
      price: 360,
      category: 'Sweets',
      subcategory: 'Regional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'baati', 'kesar', 'rajasthani']
    },
    {
      id: 'bc-16',
      title: 'Kesar-Soan-Papdi',
      url: 'https://bhikharamchandmal.in/sweets/kesar-soan-papdi.html',
      image: null,
      category: 'Sweets',
      subcategory: 'Soan Papdi',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'soan-papdi', 'kesar', 'saffron']
    },
    {
      id: 'bc-17',
      title: 'KESARIYA GANDERI',
      url: 'https://bhikharamchandmal.in/sweets/kesar-ganderi.html',
      image: null,
      price: 365,
      category: 'Sweets',
      subcategory: 'Regional Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'ganderi', 'kesar', 'specialty']
    },
    {
      id: 'bc-18',
      title: 'Khajoor Delight',
      url: 'https://bhikharamchandmal.in/sweets/khajoor%20delight.html',
      image: null,
      price: 449,
      category: 'Sweets',
      subcategory: 'Premium Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'khajoor', 'dates', 'premium']
    },
    {
      id: 'bc-19',
      title: 'Lilliput Rasgulla (Rasbhari)',
      url: 'https://bhikharamchandmal.in/sweets/liliput-rasgulla.html',
      image: null,
      price: 360,
      category: 'Sweets',
      subcategory: 'Bengali Sweets',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'rasgulla', 'lilliput', 'mini']
    },
    {
      id: 'bc-20',
      title: 'Lubhavani Soan Papdi',
      url: 'https://bhikharamchandmal.in/sweets/soanpapdi-lubhavani.html',
      image: null,
      price: 90,
      category: 'Sweets',
      subcategory: 'Soan Papdi',
      availability: 'In stock',
      companyId: 'bhikharam-chandmal',
      companyName: 'Bhikharam Chandmal',
      tags: ['sweets', 'soan-papdi', 'lubhavani', 'budget']
    }
  ]
};
