import { Company } from './types';

export const pnbKitchenmate: Company = {
  id: 'pnb-kitchenmate',
  name: 'PNB Kitchenmate',
  slug: 'pnb-kitchenmate',
  description: 'High-quality kitchenware designed to make cooking efficient and enjoyable. Specializing in triply stainless steel cookware, non-stick solutions, and innovative kitchen appliances.',
  website: 'https://www.pnbkitchenmate.com/',
  logo: 'https://www.pnbkitchenmate.com/cdn/shop/files/PNB_Kitchenmate_Logo.png',
  coverImage: 'https://www.pnbkitchenmate.com/cdn/shop/files/SmartIdlyCooker.jpg?v=1754656638&width=1946',
  category: 'Kitchenware & Cooking Equipment',
  brandColors: {
    primary: '#A93118',
    secondary: '#B8520F',
    accent: '#E18931'
  },
  contact: {
    email: 'info@pnbkitchenmate.com',
    website: 'https://www.pnbkitchenmate.com/'
  },
  specialties: [
    'Triply Stainless Steel Cookware',
    'Non-Stick Cookware',
    'Kitchen Appliances',
    'Professional Grade Equipment',
    'Durable Construction'
  ],
  certifications: [
    'Food Grade Certified',
    'Quality Assured',
    'BIS Certified'
  ],
  stats: {
    totalProducts: 20,
    avgRating: 4.5,
    yearsOfPartnership: 2
  },
  products: [
    {
      id: 'pnb-1',
      title: 'Triklass Saucepan - Triply Glass Lid Cookware 14 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-triklass-saucepan-14-cm',
      image: 'https://www.pnbkitchenmate.com/cdn/shop/products/saucepan-14cm.jpg',
      price: 1584,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Saucepans',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      description: 'Premium triply stainless steel saucepan with glass lid for efficient cooking',
      features: ['Triply construction', 'Glass lid', '14 cm diameter', 'Induction compatible'],
      tags: ['cookware', 'saucepan', 'triply', 'glass-lid']
    },
    {
      id: 'pnb-2',
      title: 'Tri-Fry Sumo Shape Karahi - Triply Cookware 24 cm',
      url: 'https://www.pnbkitchenmate.com/products/tri-fry-karahi-24-cm',
      image: null,
      price: 1804,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      description: 'Professional grade triply karahi with sumo shape design',
      features: ['Triply construction', 'Sumo shape', '24 cm diameter', 'Heat resistant handles'],
      tags: ['karahi', 'wok', 'triply', 'professional']
    },
    {
      id: 'pnb-3',
      title: 'Karahi - Triply Stainless Steel Cookware, 20 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-karahi-20-cm',
      image: null,
      price: 2754,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['karahi', 'triply', 'stainless-steel']
    },
    {
      id: 'pnb-4',
      title: 'Wok - Triply Cookware (24 cm)',
      url: 'https://www.pnbkitchenmate.com/products/triply-wok-24-cm',
      image: null,
      price: 2728,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['wok', 'triply', '24cm']
    },
    {
      id: 'pnb-5',
      title: 'Tasla - Triply Cookware 20 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-tasla-20-cm',
      image: null,
      price: 1434,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Tasla',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['tasla', 'triply', '20cm']
    },
    {
      id: 'pnb-6',
      title: 'Extra Deep Karahi - Triply Cookware, 20 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-extra-deep-karahi-20-cm',
      image: null,
      price: 2534,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['karahi', 'deep', 'triply']
    },
    {
      id: 'pnb-7',
      title: 'Cookpot - Triply Cookware 26 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-cookpot-26-cm',
      image: null,
      price: 2754,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Cookpots',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['cookpot', 'triply', '26cm']
    },
    {
      id: 'pnb-8',
      title: 'Tope with LID - Triply Cookware 14 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-tope-14-cm',
      image: null,
      price: 1584,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Topes',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['tope', 'lid', 'triply']
    },
    {
      id: 'pnb-9',
      title: 'Triklass Shallow Karahi with Glass Lid - Triply Cookware, 18 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-triklass-shallow-karahi-18-cm',
      image: null,
      price: 1646,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['karahi', 'glass-lid', 'shallow']
    },
    {
      id: 'pnb-10',
      title: 'Triklass Handi - Triply Glass Lid Cookware, 14.5 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-tricklass-handi-14-5-cm',
      image: null,
      price: 1646,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Handi',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['handi', 'glass-lid', 'triply']
    },
    {
      id: 'pnb-11',
      title: 'Triklass Frypan with Glass Lid - 18 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-triklass-frypan-18-cm',
      image: null,
      price: 1822,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Frypans',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['frypan', 'glass-lid', '18cm']
    },
    {
      id: 'pnb-12',
      title: 'Triklass Karahi - Triply Glass Lid Cookware 20 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-triklass-karahi-20-cm',
      image: null,
      price: 1804,
      category: 'Triply Stainless Steel Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['karahi', 'glass-lid', '20cm']
    },
    {
      id: 'pnb-13',
      title: 'Dosa Tawa - Inox No Oily Triply Cookware 28 cm',
      url: 'https://www.pnbkitchenmate.com/products/inox-dosa-tawa-28-cm',
      image: null,
      price: 2992,
      category: 'Inox No Oily Cookware',
      subcategory: 'Tawa',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['dosa', 'tawa', 'inox', 'no-oily']
    },
    {
      id: 'pnb-14',
      title: 'Concave Roti Tawa - Inox No Oily Triply Cookware 26 cm',
      url: 'https://www.pnbkitchenmate.com/products/inox-concave-roti-tawa-26-cm',
      image: null,
      price: 2552,
      category: 'Inox No Oily Cookware',
      subcategory: 'Tawa',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['roti', 'tawa', 'concave', 'inox']
    },
    {
      id: 'pnb-15',
      title: 'Tasla - Inox No Oily Triply Cookware',
      url: 'https://www.pnbkitchenmate.com/products/inox-tasla',
      image: null,
      price: 2288,
      category: 'Inox No Oily Cookware',
      subcategory: 'Tasla',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['tasla', 'inox', 'no-oily']
    },
    {
      id: 'pnb-16',
      title: 'Wok - Inox No Oily Triply Cookware',
      url: 'https://www.pnbkitchenmate.com/products/inox-no-oily-triply-wok',
      image: null,
      price: 3784,
      category: 'Inox No Oily Cookware',
      subcategory: 'Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['wok', 'inox', 'no-oily']
    },
    {
      id: 'pnb-17',
      title: 'Saucepan - Inox No Oily Triply Cookware, 14 cm',
      url: 'https://www.pnbkitchenmate.com/products/inox-saucepan-14-cm',
      image: null,
      price: 2746,
      category: 'Inox No Oily Cookware',
      subcategory: 'Saucepans',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['saucepan', 'inox', '14cm']
    },
    {
      id: 'pnb-18',
      title: 'Stright Frypan - Inox No Oily Triply Cookware, 16 cm',
      url: 'https://www.pnbkitchenmate.com/products/inox-stright-frypan-16-cm',
      image: null,
      price: 2895,
      category: 'Inox No Oily Cookware',
      subcategory: 'Frypans',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['frypan', 'straight', 'inox']
    },
    {
      id: 'pnb-19',
      title: 'Curve Frypan - Inox No Oily Triply Cookware, 28 cm',
      url: 'https://www.pnbkitchenmate.com/products/inox-curve-frypan-28-cm-copy',
      image: null,
      price: 2772,
      category: 'Inox No Oily Cookware',
      subcategory: 'Frypans',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['frypan', 'curve', 'inox']
    },
    {
      id: 'pnb-20',
      title: 'Karahi - Inox No Oily Triply Cookware, 26 cm',
      url: 'https://www.pnbkitchenmate.com/products/triply-triklass-shallow-karahi-26-cm-copy',
      image: null,
      price: 3256,
      category: 'Inox No Oily Cookware',
      subcategory: 'Karahi/Woks',
      availability: 'In stock',
      companyId: 'pnb-kitchenmate',
      companyName: 'PNB Kitchenmate',
      tags: ['karahi', 'inox', '26cm']
    }
  ]
};
