import { Company } from './types';

export const sarlaMills: Company = {
  id: 'sarla-mills',
  name: 'Sarla Mills',
  slug: 'sarla-mills',
  description: 'Premium textile products known for their durability and comfort. Specializing in high-quality blankets and textile solutions for institutional and retail customers.',
  website: 'https://www.sarlamills.in/',
  logo: 'https://www.sarlamills.in/cdn/shop/files/Sarla_Mills_Logo.png',
  coverImage: 'https://cdn.shopify.com/s/files/1/0683/0712/4528/files/Product-1.webp?v=1672294968',
  category: 'Textiles & Fabric Products',
  brandColors: {
    primary: '#B8520F',
    secondary: '#8B4513',
    accent: '#D2722F'
  },
  contact: {
    email: 'info@sarlamills.in',
    website: 'https://www.sarlamills.in/'
  },
  specialties: [
    'Premium Blankets',
    'Institutional Textiles',
    'Comfort Bedding',
    'Durable Fabrics',
    'Custom Solutions'
  ],
  certifications: [
    'Quality Assured',
    'Eco-Friendly Materials',
    'Durability Tested',
    'Comfort Certified'
  ],
  stats: {
    totalProducts: 20,
    avgRating: 4.4,
    yearsOfPartnership: 3
  },
  products: [
    {
      id: 'sm-1',
      title: 'AARAM Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-1',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      description: 'Premium comfort blanket designed for ultimate relaxation and warmth',
      tags: ['blanket', 'aaram', 'comfort', 'premium']
    },
    {
      id: 'sm-2',
      title: 'AARAM Handloom',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-2',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aaram', 'handloom', 'traditional']
    },
    {
      id: 'sm-3',
      title: 'AARAM Product',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-3',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aaram', 'premium']
    },
    {
      id: 'sm-4',
      title: 'AARAM Cotton Bedsheets & Pillow Covers',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-4',
      image: null,
      price: 3799,
      category: 'Bedding',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['bedsheets', 'cotton', 'pillow-covers', 'aaram']
    },
    {
      id: 'sm-5',
      title: 'AARAM Blanket and Bedsheet Set',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-5',
      image: null,
      price: 3799,
      category: 'Bedding Sets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'bedsheet', 'set', 'aaram']
    },
    {
      id: 'sm-6',
      title: 'AARAM Blanket Collection',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-6',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aaram', 'collection']
    },
    {
      id: 'sm-7',
      title: 'AARAM Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-7',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aaram', 'comfort']
    },
    {
      id: 'sm-8',
      title: 'AARAM Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/aaram-8',
      image: null,
      price: 3799,
      category: 'Blankets',
      subcategory: 'AARAM Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aaram', 'premium']
    },
    {
      id: 'sm-9',
      title: 'AARAMBH Product Page',
      url: 'https://www.sarlamills.in/collections/all/products/aarambh',
      image: null,
      price: 14999,
      category: 'Blankets',
      subcategory: 'AARAMBH Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aarambh', 'luxury', 'premium']
    },
    {
      id: 'sm-10',
      title: 'AARAMBH Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/aarambh-1',
      image: null,
      price: 14999,
      category: 'Blankets',
      subcategory: 'AARAMBH Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'aarambh', 'luxury']
    },
    {
      id: 'sm-11',
      title: 'JALSA Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsha',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'comfort']
    },
    {
      id: 'sm-12',
      title: 'JALSA Mojuri Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'mojuri']
    },
    {
      id: 'sm-13',
      title: 'JALSA Mojuri Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-1',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'mojuri']
    },
    {
      id: 'sm-14',
      title: 'JALSA Handloom Product',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-2',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'handloom']
    },
    {
      id: 'sm-15',
      title: 'JALSA - Rs. 4,899.00 - Out of Stock',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-3',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'Out of stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa']
    },
    {
      id: 'sm-16',
      title: 'JALSA Handwoven Fabric',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-4',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'handwoven']
    },
    {
      id: 'sm-17',
      title: 'JALSA Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-5',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa']
    },
    {
      id: 'sm-18',
      title: 'JALSA Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-6',
      image: null,
      price: 4899,
      category: 'Blankets',
      subcategory: 'JALSA Collection',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa']
    },
    {
      id: 'sm-19',
      title: 'JALSA AC Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-ac',
      image: null,
      price: 1799,
      category: 'Blankets',
      subcategory: 'AC Blankets',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'ac-blanket', 'summer']
    },
    {
      id: 'sm-20',
      title: 'JALSA AC Blanket',
      url: 'https://www.sarlamills.in/collections/all/products/jalsa-ac-1',
      image: null,
      price: 1799,
      category: 'Blankets',
      subcategory: 'AC Blankets',
      availability: 'In stock',
      companyId: 'sarla-mills',
      companyName: 'Sarla Mills',
      tags: ['blanket', 'jalsa', 'ac-blanket', 'summer']
    }
  ]
};
