import { Company } from './types';

export const sevenSoftIndia: Company = {
  id: 'seven-soft-india',
  name: '7Soft India',
  slug: 'seven-soft-india',
  description: "Hygienic and comfortable sanitary napkins ensuring women's health and comfort. Dedicated to providing quality hygiene products for women and babies with advanced technology.",
  website: 'https://www.7softindia.com/wp/',
  logo: 'https://www.7softindia.com/wp/wp-content/uploads/2023/01/7soft-logo.png',
  coverImage: 'https://www.7softindia.com/wp/wp-content/uploads/2023/01/website-1.jpg',
  category: 'Hygiene & Health Products',
  brandColors: {
    primary: '#A93118',
    secondary: '#dc2626',
    accent: '#F87171'
  },
  contact: {
    email: 'info@7softindia.com',
    website: 'https://www.7softindia.com/wp/'
  },
  specialties: [
    'Sanitary Napkins',
    'Baby Diapers',
    'Hygiene Products',
    'Anti-Bacterial Technology',
    'Comfort Care'
  ],
  certifications: [
    'ISO Certified',
    'Quality Assured',
    'Dermatologically Tested',
    'Anti-Bacterial Certified'
  ],
  stats: {
    totalProducts: 20,
    avgRating: 4.3,
    yearsOfPartnership: 1
  },
  products: [
    {
      id: '7si-1',
      title: '24 Care Ultra Anti Bacterial XL+ (320 mm) 1 Box (20 Pkt) Sanitary Napkins',
      url: 'https://www.7softindia.com/wp/product/24-care-ultra-anti-bacterial-xl-320-mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/10/24_care_Anti_Becteria_A-1.png',
      price: 2400,
      category: 'Sanitary Napkins',
      subcategory: '24 Care Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      description: 'Ultra-absorbent sanitary napkins with anti-bacterial technology',
      tags: ['sanitary-napkins', 'anti-bacterial', 'ultra', 'xl-plus']
    },
    {
      id: '7si-2',
      title: '24 Care Ultra Anti Bacterial XXXL  (320 mm)',
      url: 'https://www.7softindia.com/wp/product/24-care-ultra-anti-bacterial-xxxl-320-mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2024/05/24_Care_Anti_Bacterial_40Pads_B-scaled.jpg',
      price: 499,
      category: 'Sanitary Napkins',
      subcategory: '24 Care Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'anti-bacterial', 'xxxl']
    },
    {
      id: '7si-3',
      title: '7 Soft Baby Pants Style Diapers  Extra Large- XL (24 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-extra-large-xl-24-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/08/XL-1.png',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'xl-size']
    },
    {
      id: '7si-4',
      title: '7 Soft Baby Pants Style Diapers Large - L (30 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-large-l-30-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/07/7_Soft_Baby_Diaper_L1.png',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'large']
    },
    {
      id: '7si-5',
      title: '7 Soft Baby Pants Style Diapers Medium - M (34 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-medium-m-34-pieces-m/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/05/7_Soft_Baby_Diaper_L1.png',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'medium']
    },
    {
      id: '7si-6',
      title: '7 Soft Baby Pants Style Diapers Small - S (42 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-medium-m-42-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/06/7_Soft_Baby_Diaper_S.png',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'small']
    },
    {
      id: '7si-7',
      title: '7 Soft Baby Pants Style Diapers  Small- S (78 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-small-s-78-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/07/7_Soft_Baby_Diaper_JUMBO_S_2-scaled.jpg',
      price: 1099,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'small', 'bulk']
    },
    {
      id: '7si-8',
      title: '7 Soft Baby Pants Style Diapers Extra Large- XL (56 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-extra-large-xl-56-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/07/7_Soft_Baby_Diaper_JUMBO_XL_2-scaled.jpg',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'xl-size', 'bulk']
    },
    {
      id: '7si-9',
      title: '7 Soft Baby Pants Style Diapers Large - L (62 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-large-l-62-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/07/7_Soft_Baby_Diaper_JUMBO_L_1-scaled.jpg',
      price: 499,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'large', 'bulk']
    },
    {
      id: '7si-10',
      title: '7 Soft Baby Pants Style Diapers Medium- M (72 Pieces)',
      url: 'https://www.7softindia.com/wp/product/7-soft-baby-pants-style-diapers-medium-m-72-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/07/7_Soft_Baby_Diaper_JUMBO_M_2-scaled.jpg',
      price: 399,
      category: 'Baby Diapers',
      subcategory: 'Pants Style',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'medium', 'bulk']
    },
    {
      id: '7si-11',
      title: '7 Soft Maxi Cottony Care XXL – 320 mm',
      url: 'https://www.7softindia.com/wp/product/7-soft-maxi-cottony-care-xxl-320-mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2020/09/7soft-XXL.png',
      price: 399,
      category: 'Sanitary Napkins',
      subcategory: 'Maxi Care',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'maxi', 'cottony', 'xxl']
    },
    {
      id: '7si-12',
      title: '7 Soft Ultra Cottony Care XXL – 320 mm',
      url: 'https://www.7softindia.com/wp/product/7-soft-ultra-cottony-care-xxl-320-mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/05/3-2.png',
      price: 399,
      category: 'Sanitary Napkins',
      subcategory: 'Ultra Care',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'ultra', 'cottony', 'xxl']
    },
    {
      id: '7si-13',
      title: 'Extra Soft Maxi Care (XL) 280mm',
      url: 'https://www.7softindia.com/wp/product/extra-soft-maxi-care-xl-280mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/04/Extra_Soft_XXL_40pcs_2022_A.png',
      price: 349,
      category: 'Sanitary Napkins',
      subcategory: 'Extra Soft',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'extra-soft', 'maxi', 'xl']
    },
    {
      id: '7si-14',
      title: 'Extra Soft Maxi Care (XXL) 320mm',
      url: 'https://www.7softindia.com/wp/product/extra-soft-maxi-care-xxl-320mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2024/05/Extra_Soft_XXXL_40pcs_2022_B.png',
      price: 399,
      category: 'Sanitary Napkins',
      subcategory: 'Extra Soft',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'extra-soft', 'maxi', 'xxl']
    },
    {
      id: '7si-15',
      title: 'Extra Sure Maxi Care (XXXL) 320mm',
      url: 'https://www.7softindia.com/wp/product/extra-sure-maxi-care-xxxl-320mm/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/05/1-1.png',
      price: 399,
      category: 'Sanitary Napkins',
      subcategory: 'Extra Sure',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'extra-sure', 'maxi', 'xxxl']
    },
    {
      id: '7si-16',
      title: 'Extra Sure Maxi Care (XXXL) 320mm (40+10)',
      url: 'https://www.7softindia.com/wp/product/extra-sure-maxi-care-xxxl-320mm-4010/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2022/05/1.png',
      price: 399,
      category: 'Sanitary Napkins',
      subcategory: 'Extra Sure',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['sanitary-napkins', 'extra-sure', 'maxi', 'xxxl', 'bonus-pack']
    },
    {
      id: '7si-17',
      title: 'Pant Style Standard Diaper – L (75 Pieces)',
      url: 'https://www.7softindia.com/wp/product/pant-style-standard-diaper-l-75-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/08/L.png',
      price: 1099,
      category: 'Baby Diapers',
      subcategory: 'Standard Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'standard', 'large', 'bulk']
    },
    {
      id: '7si-18',
      title: 'Pant Style Standard Diaper – M (75 Pieces)',
      url: 'https://www.7softindia.com/wp/product/pant-style-standard-diaper-m-75-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/08/M.png',
      price: 1099,
      category: 'Baby Diapers',
      subcategory: 'Standard Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'standard', 'medium', 'bulk']
    },
    {
      id: '7si-19',
      title: 'Pant Style Standard Diaper – S (75 Pieces)',
      url: 'https://www.7softindia.com/wp/product/pant-style-standard-diaper-s-75-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/08/S.png',
      price: 1099,
      category: 'Baby Diapers',
      subcategory: 'Standard Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'standard', 'small', 'bulk']
    },
    {
      id: '7si-20',
      title: 'Pant Style Standard Diaper – XL (50 Pieces)',
      url: 'https://www.7softindia.com/wp/product/pant-style-standard-diaper-xl-50-pieces/',
      image: 'https://www.7softindia.com/wp/wp-content/uploads/2023/08/XL.png',
      price: 1099,
      category: 'Baby Diapers',
      subcategory: 'Standard Series',
      availability: 'In stock',
      companyId: 'seven-soft-india',
      companyName: '7Soft India',
      tags: ['baby-diapers', 'pants-style', 'standard', 'xl-size']
    }
  ]
};
