import { Company } from './types';

export const vaadiHerbals: Company = {
  id: 'vaadi-herbals',
  name: 'Vaadi Herbals',
  slug: 'vaadi-herbals',
  description: 'Natural herbal skincare and haircare products that promote wellness. Committed to bringing you the best of nature through scientifically formulated herbal products.',
  website: 'https://vaadiherbals.in/',
  logo: 'https://vaadiherbals.in/cdn/shop/files/Vaadi_Herbals_Logo.png',
  coverImage: 'https://cdn.shopify.com/s/files/1/0086/9036/8627/files/sa_my_SPF_Banner.jpg?v=1685358980',
  category: 'Herbal Care & Personal Care',
  brandColors: {
    primary: '#4B6145',
    secondary: '#2CA58D',
    accent: '#84BC9C'
  },
  contact: {
    email: 'info@vaadiherbals.in',
    website: 'https://vaadiherbals.in/'
  },
  specialties: [
    'Herbal Skincare',
    'Natural Hair Care',
    'Ayurvedic Formulations',
    'Chemical-Free Products',
    'Dermatologically Tested'
  ],
  certifications: [
    'Cruelty-Free',
    'Paraben-Free',
    'Natural Certified',
    'Dermatologically Tested',
    'ISO Certified'
  ],
  stats: {
    totalProducts: 20,
    avgRating: 4.6,
    yearsOfPartnership: 2
  },
  products: [
    {
      id: 'vh-1',
      title: '2% Alpha Arbutin Face Serum With Niacinamide & Hyaluronic Acid (30 ml)',
      url: 'https://vaadiherbals.in/products/2-alpha-arbutin-face-serum-with-niacinamide-hyaluronic-acid',
      image: null,
      price: 656,
      category: 'Face Serum',
      subcategory: 'Anti-Aging Serums',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      description: 'Advanced face serum with alpha arbutin, niacinamide, and hyaluronic acid',
      tags: ['serum', 'alpha-arbutin', 'niacinamide', 'hyaluronic-acid', 'skincare']
    },
    {
      id: 'vh-2',
      title: '2% Salicylic Acid Face Wash with AHA & Niacinamide for Oily Skin - Acne Control (110 ml)',
      url: 'https://vaadiherbals.in/products/2-salicylic-acid-face-wash-with-aha-niacinamide-for-oily-skin-acne-control-reduces-pimples-and-breakouts-no-parabens-mineral-silicon-face-wash-for-women-men-110-ml',
      image: null,
      price: 276,
      category: 'Face Wash',
      subcategory: 'Acne Control',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'salicylic-acid', 'acne', 'oily-skin']
    },
    {
      id: 'vh-3',
      title: '2% Salicylic Acid Face Wash with AHA & Niacinamide for Oily Skin - 250 ml',
      url: 'https://vaadiherbals.in/products/2-salicylic-acid-face-wash-with-aha-niacinamide-for-oily-skin-acne-control-reduces-pimples-and-breakouts-no-parabens-mineral-silicon-face-wash-for-women-men-250-ml',
      image: null,
      price: 461,
      category: 'Face Wash',
      subcategory: 'Acne Control',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'salicylic-acid', 'acne', 'oily-skin', '250ml']
    },
    {
      id: 'vh-4',
      title: '20% Vitamin C Face Serum With Advanced Brightening Formula (30 ml)',
      url: 'https://vaadiherbals.in/products/20-vitamin-c-face-serum-with-advanced-brightening-formula-30-ml',
      image: null,
      price: 656,
      category: 'Face Serum',
      subcategory: 'Brightening Serums',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['serum', 'vitamin-c', 'brightening', 'skincare']
    },
    {
      id: 'vh-5',
      title: '24 Carat Gold Cleansing Cream with Marigold Oil & Wheatgerm Oil (50 gms)',
      url: 'https://vaadiherbals.in/products/24-carat-gold-cleansing-cream-marigold-oil-wheatgerm-oil-50-gms',
      image: null,
      price: 281,
      category: 'Cleansing Cream',
      subcategory: 'Gold Series',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['cleansing-cream', 'gold', 'marigold', 'wheatgerm']
    },
    {
      id: 'vh-6',
      title: '24 Carat Gold Face Pack - Vitamin-E & Lemon Peel (70 gms)',
      url: 'https://vaadiherbals.in/products/24-carat-gold-face-pack-vitamin-e-lemon-peel-70-gms',
      image: null,
      price: 304,
      category: 'Face Pack',
      subcategory: 'Gold Series',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-pack', 'gold', 'vitamin-e', 'lemon']
    },
    {
      id: 'vh-7',
      title: '24 Carat Gold Massage Cream - Kokum Butter & Wheatgerm Oil (50 gms)',
      url: 'https://vaadiherbals.in/products/24-carat-gold-massage-cream-kokum-butter-wheatgerm-oil-50-gms',
      image: null,
      price: 281,
      category: 'Massage Cream',
      subcategory: 'Gold Series',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['massage-cream', 'gold', 'kokum-butter', 'wheatgerm']
    },
    {
      id: 'vh-8',
      title: '24 Carat Gold Massage Gel - 24 Carat Gold Dust & Grape Seed Extract (50 gms)',
      url: 'https://vaadiherbals.in/products/24-carat-gold-massage-gel-24-carat-gold-dust-grape-seed-extract-50-gms',
      image: null,
      price: 304,
      category: 'Massage Gel',
      subcategory: 'Gold Series',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['massage-gel', 'gold', 'grape-seed', 'luxury']
    },
    {
      id: 'vh-9',
      title: '24 Carat Gold Scrub - Sandalwood & Turmeric (50 gms)',
      url: 'https://vaadiherbals.in/products/24-carat-gold-scrub-sandalwood-turmeric-50-gms',
      image: null,
      price: 281,
      category: 'Face Scrub',
      subcategory: 'Gold Series',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['scrub', 'gold', 'sandalwood', 'turmeric']
    },
    {
      id: 'vh-10',
      title: '3% Salicylic Acid + 1% Piroctone Olamine Anti Dandruff Hair Serum (30 ml)',
      url: 'https://vaadiherbals.in/products/3-salicylic-acid-1-piroctone-olamine-anti-dandruff-hair-serum-30-ml',
      image: null,
      price: 656,
      category: 'Hair Serum',
      subcategory: 'Anti-Dandruff',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['hair-serum', 'anti-dandruff', 'salicylic-acid', 'piroctone']
    },
    {
      id: 'vh-11',
      title: '3% Tranexamic & 10% Azelaic Acid Anti-Pigmentation Serum with 5% Niacinamide (30 ml)',
      url: 'https://vaadiherbals.in/products/3-tranexamic-and-10-azelaic-acid-anti-pigmentation-serum-with-5-niacinamide-brighter-complexion-reduces-dark-spots-soothes-inflammation-fades-hyper-pigmentation-for-all-skin-types-30ml',
      image: null,
      price: 656,
      category: 'Face Serum',
      subcategory: 'Anti-Pigmentation',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['serum', 'anti-pigmentation', 'tranexamic', 'azelaic-acid']
    },
    {
      id: 'vh-12',
      title: 'Acne Treatment Set - Aloe Vera - Removes Acne & Pimple Marks (285 gms)',
      url: 'https://vaadiherbals.in/products/acne-treatment-set-aloe-vera-removes-acne-pimple-marks-285-gms',
      image: null,
      price: 643,
      category: 'Treatment Set',
      subcategory: 'Acne Care',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['acne-treatment', 'aloe-vera', 'pimple-marks', 'set']
    },
    {
      id: 'vh-13',
      title: 'Activated Charcoal Face Wash with Tea Tree Oil & Glycolic Acid for Oily, Acne-Prone Skin (110 ml)',
      url: 'https://vaadiherbals.in/products/activated-charcoal-face-wash-with-tea-tree-oil-bentonite-clay-glycolic-acid-for-oily-acne-prone-skin-detoxifies-refreshes-deep-purify-no-parabens-mineral-silicon-face-wash-for-women-men-110ml',
      image: null,
      price: 276,
      category: 'Face Wash',
      subcategory: 'Charcoal Care',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'charcoal', 'tea-tree', 'acne-prone']
    },
    {
      id: 'vh-14',
      title: 'Activated Charcoal Face Wash with Tea Tree Oil & Glycolic Acid for Oily & Acne-Prone Skin (250 ml)',
      url: 'https://vaadiherbals.in/products/activated-charcoal-face-wash-with-tea-tree-oil-bentonite-clay-glycolic-acid-for-oily-acne-prone-skin-detoxifies-refreshes-deep-purify-no-parabens-mineral-silicon-face-wash-for-women-men-250-ml',
      image: null,
      price: 461,
      category: 'Face Wash',
      subcategory: 'Charcoal Care',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'charcoal', 'tea-tree', 'acne-prone', '250ml']
    },
    {
      id: 'vh-15',
      title: 'Activated Charcoal Soap (75 gms) – Vaadi Herbals',
      url: 'https://vaadiherbals.in/products/activated-charcoal-soap-75-gms',
      image: null,
      price: 61,
      category: 'Soap',
      subcategory: 'Charcoal Care',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['soap', 'charcoal', 'natural', 'detox']
    },
    {
      id: 'vh-16',
      title: 'Advanced Brightening Vitamin C Face Wash with Pro Vitamin B5 & Turmeric (110 ml)',
      url: 'https://vaadiherbals.in/products/advanced-brightening-vitamin-c-face-wash-with-pro-vitamin-b5-turmeric-110-ml',
      image: null,
      price: 138,
      category: 'Face Wash',
      subcategory: 'Brightening',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'vitamin-c', 'brightening', 'turmeric']
    },
    {
      id: 'vh-17',
      title: 'Advanced Brightening Vitamin C Face Wash With Pro Vitamin B5 & Turmeric (2 x 110 ml)',
      url: 'https://vaadiherbals.in/products/advanced-brightening-vitamin-c-face-wash-with-pro-vitamin-b5-turmeric-2-x-110-ml',
      image: null,
      price: 276,
      category: 'Face Wash',
      subcategory: 'Brightening',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'vitamin-c', 'brightening', 'twin-pack']
    },
    {
      id: 'vh-18',
      title: 'Advanced Brightening Vitamin C Face Wash with Pro Vitamin B5 & Turmeric (250 ml)',
      url: 'https://vaadiherbals.in/products/copy-of-advanced-brightening-vitamin-c-face-wash-with-pro-vitamin-b5-turmeric-250-ml-4-fl-oz',
      image: null,
      price: 271,
      category: 'Face Wash',
      subcategory: 'Brightening',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['face-wash', 'vitamin-c', 'brightening', '250ml']
    },
    {
      id: 'vh-19',
      title: 'Age Defying Blueberry & Grapefruit Hand Wash (250 ml)',
      url: 'https://vaadiherbals.in/products/age-defying-blueberry-grapefruit-hand-wash-250-ml',
      image: null,
      price: 138,
      category: 'Hand Wash',
      subcategory: 'Age Defying',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['hand-wash', 'blueberry', 'grapefruit', 'age-defying']
    },
    {
      id: 'vh-20',
      title: 'All Day Fairness Body Lotion with 100% Pure Sargol Saffron & Goat Milk (250 ml / 8.5 fl oz)',
      url: 'https://vaadiherbals.in/products/all-day-fairness-body-lotion-with-100-pure-sargol-saffron-goat-milk-250-ml-8-5-fl-oz',
      image: null,
      price: 271,
      category: 'Body Lotion',
      subcategory: 'Fairness',
      availability: 'In stock',
      companyId: 'vaadi-herbals',
      companyName: 'Vaadi Herbals',
      tags: ['body-lotion', 'fairness', 'saffron', 'goat-milk']
    }
  ]
};
